version: "3.8" # version of code to utilize in this file


services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    command: sh -c "alembic -c resources/alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - certs_volume:/certs
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
    name: ${DB_CONTAINER_NAME}
  certs_volume:
    name: ${APP_CONTAINER_NAME}
